const con_3 = { 
  isFlippedHorizontal: 0,
  includeBackgroundColorInInstance: 0,
  objectID: '3D4E2509-C562-4A77-965B-C23620054B0C',
  horizontalRulerData: { '<class>': 'MSRulerData', base: 0, guides: [] },
  frame:
   { y: 878,
     '<class>': 'MSRect',
     constrainProportions: 0,
     height: 29,
     width: 300,
     x: 1209 },
  hasClickThrough: 1,
  includeInCloudUpload: 1,
  exportOptions:
   { shouldTrim: 0,
     '<class>': 'MSExportOptions',
     includedLayerIds: [],
     layerOptions: 0,
     exportFormats: [] },
  hasBackgroundColor: 1,
  layerListExpandedType: 0,
  resizesContent: 0,
  backgroundColor: { '<class>': 'MSColor', value: '#FAFAFA' },
  rotation: 0,
  style:
   { startDecorationType: 0,
     borderOptions:
      { lineJoinStyle: 0,
        '<class>': 'MSStyleBorderOptions',
        isEnabled: 0,
        lineCapStyle: 0,
        dashPattern: [] },
     endDecorationType: 0,
     contextSettings:
      { '<class>': 'MSGraphicsContextSettings',
        opacity: 1,
        blendMode: 0 },
     blur:
      { radius: 10,
        '<class>': 'MSStyleBlur',
        motionAngle: 0,
        isEnabled: 0,
        type: 0,
        center: [Object] },
     reflection:
      { '<class>': 'MSStyleReflection',
        strength: 0.5,
        isEnabled: 0,
        distance: 1 },
     '<class>': 'MSStyle',
     miterLimit: 10,
     colorControls:
      { hue: 0,
        '<class>': 'MSStyleColorControls',
        brightness: 0,
        contrast: 1,
        isEnabled: 0,
        saturation: 1 },
     fills: [ [Object] ],
     borders: [],
     innerShadows: [],
     shadows: [] },
  symbolID: 'E7416D03-9243-45B3-881F-FCD00244CD86',
  verticalRulerData: { '<class>': 'MSRulerData', base: 0, guides: [] },
  isFlippedVertical: 0,
  '<class>': 'MSSymbolMaster',
  nameIsFixed: 1,
  layers:
   [ { isFlippedHorizontal: 0,
       style: [Object],
       rotation: 0,
       frame: [Object],
       hasClickThrough: 0,
       objectID: 'D8A3B984-80C6-4E15-8DC5-B6536CF0B6C5',
       exportOptions: [Object],
       layerListExpandedType: 1,
       windingRule: 1,
       isFlippedVertical: 0,
       clippingMaskMode: 0,
       resizingType: 0,
       layers: [Array],
       isVisible: 1,
       hasClippingMask: 1,
       '<class>': 'MSShapeGroup',
       nameIsFixed: 0,
       name: 'Mask',
       isLocked: 0,
       shouldBreakMaskChain: 0,
       resizingConstraint: 63 },
     { shouldBreakMaskChain: 0,
       style: [Object],
       rotation: 0,
       layers: [Array],
       exportOptions: [Object],
       frame: [Object],
       isFlippedVertical: 0,
       hasClickThrough: 0,
       isVisible: 1,
       objectID: 'CFEF28F3-8E3E-450E-B945-2E06DC4A136E',
       resizingConstraint: 63,
       isFlippedHorizontal: 0,
       resizingType: 0,
       '<class>': 'MSLayerGroup',
       isLocked: 0,
       layerListExpandedType: 0,
       nameIsFixed: 1,
       name: 'Tab 3' },
     { shouldBreakMaskChain: 0,
       style: [Object],
       rotation: 0,
       layers: [Array],
       exportOptions: [Object],
       frame: [Object],
       isFlippedVertical: 0,
       hasClickThrough: 0,
       isVisible: 1,
       objectID: '11B7CEFC-6EE7-42C5-B655-2766A9C4370B',
       resizingConstraint: 63,
       isFlippedHorizontal: 0,
       resizingType: 0,
       '<class>': 'MSLayerGroup',
       isLocked: 0,
       layerListExpandedType: 0,
       nameIsFixed: 1,
       name: 'Tab 2' },
     { shouldBreakMaskChain: 0,
       style: [Object],
       rotation: 0,
       layers: [Array],
       exportOptions: [Object],
       frame: [Object],
       isFlippedVertical: 0,
       hasClickThrough: 0,
       isVisible: 1,
       objectID: '4594124B-FEEF-48E2-82AB-D8A69D1E8E43',
       resizingConstraint: 63,
       isFlippedHorizontal: 0,
       resizingType: 0,
       '<class>': 'MSLayerGroup',
       isLocked: 0,
       layerListExpandedType: 0,
       nameIsFixed: 1,
       name: 'Tab 1' } ],
  isVisible: 1,
  name: 'Basic Elements/Controls/Segmented Control/3-1',
  resizingType: 0,
  isLocked: 0,
  shouldBreakMaskChain: 0,
  resizingConstraint: 63,
  includeBackgroundColorInExport: 0 }

module.exports = con_3